workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.ea.atesiask"
        DEVELOPMENT_TEAM: "76J8JGV82N"
        PROVISIONING_PROFILE: "Provisioning Profile"
      groups:
        - signing_credentials

    scripts:
      - name: Clean workspace
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Configure signing
        script: |
          /usr/libexec/PlistBuddy -c "Set :PROVISIONING_PROFILE_SPECIFIER 'Provisioning Profile'" ios/Runner.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :CODE_SIGN_STYLE Manual" ios/Runner.xcodeproj/project.pbxproj
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY