workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.ea.atesiask"
      groups:
        - signing_credentials

    scripts:
      - name: Clean workspace
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Verify entitlements
        script: |
          # Ensure entitlements contain Associated Domains
          if ! grep -q "associated-domains" ios/Runner/Runner.entitlements; then
            echo 'Adding Associated Domains to entitlements'
            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.associated-domains array" ios/Runner/Runner.entitlements
            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.associated-domains:0 string 'applinks:example.com'" ios/Runner/Runner.entitlements
          fi

      - name: Configure signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
