workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.ea.atesiask"
      groups:
        - signing_credentials

    scripts:
      - name: Clean build
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm ios/Podfile.lock

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up signing
        script: |
          sed -i '' 's/RunnerDebug\.entitlements/Runner\.entitlements/g' ios/Runner.xcodeproj/project.pbxproj
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
