workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.ea.atesiask"
        DEVELOPMENT_TEAM: "76J8JGV82N"
        PROVISIONING_PROFILE_SPECIFIER: "Provisioning Profile"
      groups:
        - signing_credentials

    scripts:
      - name: Set up environment
        script: |
          # Flutter ve Xcode versiyonlarını kontrol et
          flutter --version
          xcodebuild -version
          
      - name: Clean workspace
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -f ios/Podfile.lock
          rm -rf build/
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Setup iOS dependencies
        script: |
          cd ios
          # Podfile'ı kontrol et ve gerekirse güncelle
          pod repo update
          pod install --verbose
          cd ..

      - name: Create archive directory
        script: |
          mkdir -p /Users/builder/clone/build/ios/xcarchive
          mkdir -p /Users/builder/clone/build/ios/ipa

      - name: Build Flutter iOS
        script: |
          # iOS projesi konfigürasyonunu kontrol et
          cd ios
          pod install --repo-update
          cd ..
          
          # Flutter cache'ini temizle
          flutter clean
          flutter pub get
          
          # iOS build'ini debug bilgileri ile yap
          flutter build ios --release --no-codesign --verbose

      - name: Archive iOS App
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath /Users/builder/clone/build/ios/xcarchive/Runner.xcarchive \
            archive \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath /Users/builder/clone/build/ios/xcarchive/Runner.xcarchive \
            -exportPath /Users/builder/clone/build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa