workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.ea.atesiask"
      groups:
        - signing_credentials  # Codemagic panelinde tanımlı sertifika ve profil grubu

    scripts:
      - name: Flutter temizleme
        script: |
          flutter clean
          flutter pub get
      - name: Configure code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --config Release \
            --export-options-plist ios/exportOptions.plist
      - name: Verify code signing
        script: |
          codesign -v build/ios/ipa/*.ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
