// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:bizidealcennetine/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLz14YRKqdhLSzFKr--TRciwzlfhfBRBk',
    appId: '1:747551272671:android:d705482ed7be7dc31cc36a',
    messagingSenderId: '747551272671',
    projectId: 'atesiask-ea0ba',
    databaseURL: 'https://atesiask-ea0ba.firebaseio.com',
    storageBucket: 'atesiask-ea0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZT89hDp7yxgN_pBVtfYvi-ycfTFG2Ixo',
    appId: '1:747551272671:ios:a4ec05f960c312a81cc36a',
    messagingSenderId: '747551272671',
    projectId: 'atesiask-ea0ba',
    databaseURL: 'https://atesiask-ea0ba.firebaseio.com',
    storageBucket: 'atesiask-ea0ba.appspot.com',
    androidClientId: '747551272671-08ilnkg8nt61s9c77og7t7fc57nvcku2.apps.googleusercontent.com',
    iosClientId: '747551272671-h13c59d9lfrbf3clomv1ltvll6fcq5do.apps.googleusercontent.com',
    iosBundleId: 'com.ea.atesiask',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3ANa3TWZWSMZlRZLTYRIMku3PtmgUkk',
    appId: '1:747551272671:web:765ddf483d97b6f61cc36a',
    messagingSenderId: '747551272671',
    projectId: 'atesiask-ea0ba',
    authDomain: 'atesiask-ea0ba.firebaseapp.com',
    databaseURL: 'https://atesiask-ea0ba.firebaseio.com',
    storageBucket: 'atesiask-ea0ba.appspot.com',
    measurementId: 'G-Q8FCTXVEVV',
  );

}